# Generated by Django 5.1 on 2024-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(blank=True, choices=[(2, '2 Persons'), (4, '4 Persons'), (6, '6 Persons'), (8, '8 Persons')], default=4, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('suv', 'SUV'), ('mpv', 'MPV'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback')], default='sedan', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='gasoline_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, default=70.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='steering',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10, null=True),
        ),
    ]
