# Generated by Django 5.1 on 2024-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_capacity_car_car_type_car_gasoline_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
