# Generated by Django 4.2.11 on 2024-09-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_car_type_alter_car_steering'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
